# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Psalm Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '23 9 * * 2'

permissions:
  contents: read

jobs:
  psalm-security-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.2, 7.3, 7.4]
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set safe directory
        run: git config --global --add safe.directory /github/workspace

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Run composer update if PHP version >= 8.0
        if: startsWith(matrix.php-version, '8.')
        run: composer update --no-scripts --no-progress --no-dev
        working-directory: ./web

      - name: Install dependencies
        run: composer install --no-scripts --no-progress --no-dev
        working-directory: ./web

      - name: Psalm Security Scan
        uses: docker://ghcr.io/psalm/psalm-security-scan:5.7.7 # version supporting PHP 7.4
        env:
          INPUT_WORKING_DIR: ./web

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./web/results.sarif